required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
  "github.com/knative/build/pkg/apis/build/v1alpha1",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/test-infra"
  non-go = false

[[override]]
  name = "github.com/knative/pkg"
  revision = "0f749ef7d5e65aba4e8a76aa34b4744685981a91"

[[override]]
  name = "github.com/knative/eventing"
  revision = "b437219896ceb21556e42701ac03478b582f8c1f"

[[override]]
  name = "github.com/knative/serving"
  revision = "3557f16e40c47bebd38be7d38844c6f44a83ba33"
