apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knap-graph
  labels:
    knative.dev/type: "function"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          serviceAccountName: knap
          container:
            image: github.com/n3wscott/knap/cmd/graph/
